/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "2FA": {                                         "en": "Key for two-step verification",                   "de": "Key für 2 Faktor-Authentifizierung",              "ru": "Ключ для двухэтапной проверки",                   "pt": "Chave para verificação em duas etapas",           "nl": "Sleutel voor tweestapsverificatie",               "fr": "Clé pour la vérification en deux étapes",         "it": "Chiave per la verifica in due passaggi",          "es": "Clave para la verificación en dos pasos.",        "pl": "Klucz do weryfikacji dwuetapowej",                "zh-cn": "两步验证的关键"},
    "Find my iPhone": {                              "en": "Find my iPhone",                                  "de": "Findw mein iPhone Einstellungen",                 "ru": "Пример",                                          "pt": "Encontre meu iphone",                             "nl": "Vind mijn iphone",                                "fr": "Trouve mon iphone",                               "it": "Trova il mio iPhone",                             "es": "Encontrar mi iphone",                             "pl": "Znajdź mojego IPhone'a",                          "zh-cn": "查找我的iPhone"},
    "Settings": {                                    "en": "Settings",                                        "de": "Einstellungen",                                   "ru": "Settings",                                        "pt": "Definições",                                      "nl": "instellingen",                                    "fr": "Réglages",                                        "it": "impostazioni",                                    "es": "Ajustes",                                         "pl": "Ustawienia",                                      "zh-cn": "设置"},
    "Step1": {                                       "en": "Step 1: Fill out only username and password, Save and start the adapter", "de": "Step 1: Nur den Usernamen und das Passwort einragen, speichern und den adapter starten.", "ru": "Шаг 1: Заполните только имя пользователя и пароль, сохраните и запустите адаптер", "pt": "Passo 1: Preencha apenas o nome de usuário e senha, salve e inicie o adaptador", "nl": "Stap 1: Vul alleen gebruikersnaam en wachtwoord in, sla op en start de adapter", "fr": "Étape 1: indiquez uniquement le nom d'utilisateur et le mot de passe, enregistrez et démarrez l'adaptateur", "it": "Passaggio 1: compilare solo nome utente e password, salvare e avviare l'adattatore", "es": "Paso 1: complete solo el nombre de usuario y la contraseña, guarde e inicie el adaptador", "pl": "Krok 1: Wypełnij tylko nazwę użytkownika i hasło, Zapisz i uruchom adapter", "zh-cn": "步骤1：仅填写用户名和密码，保存并启动适配器"},
    "Step2": {                                       "en": "Step 2: Confirm your registration on one of your devices.", "de": "Step 2: Registrierung auf irgendeinem deiner Gerät bestätigen.", "ru": "Шаг 2: Подтвердите регистрацию на одном из ваших устройств.", "pt": "Etapa 2: confirme seu registro em um dos seus dispositivos.", "nl": "Stap 2: Bevestig uw registratie op een van uw apparaten.", "fr": "Étape 2: Confirmez votre inscription sur l’un de vos appareils.", "it": "Passaggio 2: conferma la registrazione su uno dei tuoi dispositivi.", "es": "Paso 2: Confirma tu registro en uno de tus dispositivos.", "pl": "Krok 2: Potwierdź rejestrację na jednym ze swoich urządzeń.", "zh-cn": "第2步：确认您在其中一台设备上的注册。"},
    "Step3": {                                       "en": "Step 3: Now enter the 6-digit code in the Key-Field.", "de": "Step 3: Nur den 6-stelligen Code ins Key-Feld eintragen.", "ru": "Шаг 3: Теперь введите 6-значный код в поле ключа.", "pt": "Passo 3: Agora digite o código de 6 dígitos no campo-chave.", "nl": "Stap 3: Voer nu de 6-cijferige code in het Key-Field in.", "fr": "Étape 3: Maintenant, entrez le code à 6 chiffres dans le champ clé.", "it": "Passo 3: Ora inserisci il codice a 6 cifre nel campo chiave.", "es": "Paso 3: Ahora ingrese el código de 6 dígitos en el campo clave.", "pl": "Krok 3: Teraz wprowadź 6-cyfrowy kod w polu klucza.", "zh-cn": "第3步：现在在Key-Field中输入6位数代码。"},
    "Two-step verification": {                       "en": "Two-step verification:",                          "de": "Zwei-Faktor-Authentifizierung:",                  "ru": "Двухэтапная проверка:",                           "pt": "Verificação em duas etapas:",                     "nl": "Tweestapsverificatie:",                           "fr": "Vérification en deux étapes:",                    "it": "Verifica in due passaggi:",                       "es": "Verificación de dos pasos:",                      "pl": "Weryfikacja dwuetapowa:",                         "zh-cn": "两步验证："},
    "leave empty": {                                 "en": "(else leave enpty)",                              "de": "(sonst frei lassen)",                             "ru": "(иначе оставьте enpty)",                          "pt": "(senão deixe enpty)",                             "nl": "(laat anders enpty)",                             "fr": "(sinon laisser enpty)",                           "it": "(altrimenti lascia enpty)",                       "es": "(si no deja enpty)",                              "pl": "(inaczej zostawić enpty)",                        "zh-cn": "（否则请留下enpty）"},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern der Einstellungen wird der Adapter automatisch neu gestartet.", "ru": "Сразу после сохранения настроек драйвер перезапуститься с новыми значениями", "pt": "on save adapter reinicia com nova configuração imediatamente", "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config", "fr": "sur save, l'adaptateur redémarre immédiatement avec la nouvelle configuration", "it": "su save adapter si riavvia immediatamente con la nuova configurazione", "es": "en guardar adaptador se reinicia con nueva configuración inmediatamente", "pl": "na adapterze natychmiast uruchamia się ponownie z nową konfiguracją", "zh-cn": "保存适配器立即重新启动新配置"}
    "pollIntervall": {                               "en": "Poll Intervall",                                  "de": "Pollintervall",                                   "ru": "Опрос Интервал",                                  "pt": "Poll Intervall",                                  "nl": "Poll Intervall",                                  "fr": "Sondage Intervall",                               "it": "Poll Intervall",                                  "es": "Encuesta Intervall",                              "pl": "Ankieta Intervall",                               "zh-cn": "民意调查Intervall"},
};